In [1]:
import MetaTrader5 as mt5
import pandas as pd

In [2]:
mt5.initialize(  # initialize es un metodo de la api de mt5 para coneccion
                 path="C:\\Program Files\\MetaTrader 5\\terminal64.exe",
                 login=112290489,
                 password="-7GtHiVi",
                 server="MetaQuotes-Demo",
                 timeout=60000,
                 portable=False)

True

In [3]:
pd.DataFrame(mt5.copy_rates_from_pos("EURUSD",
                        mt5.TIMEFRAME_H1,
                          0, 
                          5))

,time,open,high,low,close,tick_volume,spread,real_volume
0,1788811200,1.16286,1.16287,1.16244,1.16255,1146,0,0
1,1788814800,1.16255,1.16258,1.16229,1.16236,959,0,0
2,1788818400,1.16236,1.16237,1.16211,1.16222,1018,0,0
3,1788822000,1.16222,1.16232,1.16214,1.16228,1798,0,0
4,1788825600,1.16232,1.16237,1.16232,1.16237,3,0,0

In [6]:
import pandas as pd
symbol = "EURUSD"
tf = mt5.TIMEFRAME_H1
from_position = 1
num_bars= 1 #ultima vela cerrada

bars = pd.DataFrame(mt5.copy_rates_from_pos(symbol, tf, from_position, num_bars)) # Copiar los datos de las velas
bars['time'] = pd.to_datetime(bars['time'], unit='s') #formato del tiempo
bars.set_index('time', inplace=True) #establecer el tiempo como indice

bars.rename(columns={'tick_volume': 'tickvol', 'real_volume': 'vol'}, inplace=True)
bars = bars[['open', 'high', 'low', 'close', 'tickvol', 'vol', 'spread']]
bars

                        open     high      low    close  tickvol  vol  spread
time
2026-09-10 17:00:00  1.16113  1.16295  1.16113  1.16294    16727    0       0

In [8]:
def get_latest_tick(symbol: str) -> dict:
        try:
            tick = mt5.symbol_info_tick(symbol)
            if tick is None:
                print(f" No se ha podido recuperar el último tick de {symbol} - MT5 error: {mt5.last_error()}")
                return {} #devuelve un diccionario vacío si no se puede recuperar el tick
        
        except Exception as e:
            print(f"Algo no ha ido bien a la hora de recuperar el último tick de {symbol}. MT5 error: {mt5.last_error()}, exception: {e}")
        
        else:
            return tick._asdict()

get_latest_tick("EURUSD")

{'time': 1789067700,
 'bid': 1.1625,
 'ask': 1.1625,
 'last': 0.0,
 'volume': 0,
 'time_msc': 1789067700233,
 'flags': 1028,
 'volume_real': 0.0}