In [43]:
import MetaTrader5 as mt5
import pandas as pd

In [44]:
mt5.initialize(  # initialize es un metodo de la api de mt5 para coneccion
                 path="C:\\Program Files\\MetaTrader 5\\terminal64.exe",
                 login=112290489,
                 password="-7GtHiVi",
                 server="MetaQuotes-Demo",
                 timeout=60000,
                 portable=False)

True

In [45]:
pd.DataFrame(mt5.copy_rates_from_pos("EURUSD",
                        mt5.TIMEFRAME_H1,
                          0, 
                          5))

,time,open,high,low,close,tick_volume,spread,real_volume
0,1788796800,1.16250,1.16296,1.16239,1.16289,5776,0,0
1,1788800400,1.16289,1.16330,1.16271,1.16312,6647,0,0
2,1788804000,1.16312,1.16320,1.16264,1.16276,4213,0,0
3,1788807600,1.16276,1.16299,1.16260,1.16286,1619,0,0
4,1788811200,1.16286,1.16287,1.16259,1.16261,408,0,0

In [ ]:
import pandas as pd
symbol = "EURUSD"
tf = mt5.TIMEFRAME_H1
from_position = 1
num_bars= 1

bars = pd.DataFrame(mt5.copy_rates_from_pos(symbol, tf, from_position, num_bars))
bars['time'] = pd.to_datetime(bars['time'], unit='s')
bars

,time,open,high,low,close,tick_volume,spread,real_volume
0,2026-09-07 18:00:00,1.16312,1.1632,1.16264,1.16276,4213,0,0